import { useContext, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import LoadingPage from "../components/ui/LoadingPage";
import { AddressModalContext } from "../context/AddressModalContext";
import { useAuth } from "../hooks/useAuth";
import { useCart } from "../hooks/useCart";
import { useCheckout } from "../hooks/useCheckout";
import { placeOrders } from "../service/orderService";
import {
  createRazorpayOrder,
  loadRazorpayScript,
  verifyPayment,
} from "../service/paymentService";

const PaymentPage = () => {
  const { cartItems = [], cart = { grandTotal: 0 } } = useCart();
  const [razorpayOrderId, setRazorpayOrderId] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);
  const { selectedAddress } = useContext(AddressModalContext);
  const { completeStep } = useCheckout();
  const { user } = useAuth();
  const navigate = useNavigate();

  useEffect(() => {
    const createPaymentOrder = async () => {
      try {
        if (
          !user?.userId ||
          !cart.grandTotal ||
          cartItems.length === 0 ||
          !selectedAddress
        ) {
          throw new Error("Missing required data to initiate payment.");
        }

        const scriptLoaded = await loadRazorpayScript();
        if (!scriptLoaded) throw new Error("Failed to load Razorpay SDK");

        const payload = {
          amount: Math.round(cart.grandTotal),
          currency: "INR",
          customerId: user.userId,
          orderId: null, // This will be generated by backend
        };

        console.log("Creating Razorpay order with payload:", payload);
        const response = await createRazorpayOrder(payload);

        if (!response?.id) {
          console.error("Invalid Razorpay response:", response);
          throw new Error(
            "Razorpay order creation failed - no order ID returned"
          );
        }

        console.log("Razorpay order created successfully:", response.id);
        setRazorpayOrderId(response.id);
      } catch (err) {
        console.error("Payment initialization error:", err);
        setError(err.message || "Unable to initialize payment.");
      } finally {
        setIsLoading(false);
      }
    };

    createPaymentOrder();
  }, [cart, cartItems, user, selectedAddress]);

  const handlePayment = async () => {
    if (!razorpayOrderId) {
      setError("Payment is not ready.");
      return;
    }

    try {
      setIsLoading(true);
      setError(null);

      // First place the order to get orderId
      const orderPayload = {
        userId: user.userId,
        items: cartItems.map((item) => ({
          productId: item.productId,
          productName: item.productName,
          size: item.size,
          color: item.color,
          quantity: item.quantity,
          price: item.price,
          total: item.price * item.quantity,
          image: item.image,
        })),
        shippingAddress: selectedAddress,
        totalAmount: cart.grandTotal,
        paymentMethod: "ONLINE",
        deliveryCharges: 0,
      };

      console.log("Placing order with payload:", orderPayload);
      const placedOrder = await placeOrders(orderPayload);

      if (!placedOrder?.orderId) {
        throw new Error("Failed to create order - no order ID returned");
      }

      console.log("Order placed successfully:", placedOrder.orderId);

      const options = {
        key: import.meta.env.VITE_RAZORPAY_KEY_ID,
        amount: Math.round(cart.grandTotal * 100), // Convert to paise
        currency: "INR",
        name: "28 Miles",
        description: `Order #${placedOrder.orderId}`,
        order_id: razorpayOrderId,
        prefill: {
          name: selectedAddress.fullName,
          email: selectedAddress.email || user.email || "",
          contact: selectedAddress.phone,
        },
        notes: {
          customer_id: user.userId,
          order_id: placedOrder.orderId,
        },
        theme: {
          color: "#0f172a",
        },
        handler: async function (paymentResponse) {
          await handlePaymentSuccess(paymentResponse, placedOrder.orderId);
        },
        modal: {
          ondismiss: function () {
            console.log("Payment modal dismissed");
            setIsLoading(false);
          },
        },
      };

      console.log("Opening Razorpay with options:", {
        ...options,
        key: "***HIDDEN***", // Hide key in logs
      });

      const rzp = new window.Razorpay(options);

      rzp.on("payment.failed", (res) => {
        console.error("Payment failed event:", res);
        handlePaymentFailure(res.error);
      });

      rzp.open();
    } catch (err) {
      console.error("Payment initiation error:", err);
      setError(err.message || "Failed to initiate payment.");
      setIsLoading(false);
    }
  };

  const handlePaymentSuccess = async (paymentResponse, orderId) => {
    try {
      console.log("Payment successful, verifying...", paymentResponse);

      const verificationData = {
        orderId: orderId, // Use the actual order ID from backend
        razorpayOrderId: paymentResponse.razorpay_order_id,
        razorpayPaymentId: paymentResponse.razorpay_payment_id,
        razorpaySignature: paymentResponse.razorpay_signature,
      };

      console.log("Verifying payment with data:", verificationData);
      const verificationResult = await verifyPayment(verificationData);

      console.log("Payment verification result:", verificationResult);

      // Complete checkout steps
      completeStep("payment");
      completeStep("success");

      // Navigate to success page
      navigate("/payment-success", {
        state: {
          ...paymentResponse,
          orderDetails: verificationResult,
          orderId: orderId,
        },
      });
    } catch (err) {
      console.error("Payment verification error:", err);
      setError(
        err.message ||
          "Payment was processed but verification failed. Please contact support with your payment details."
      );
    } finally {
      setIsLoading(false);
    }
  };

  const handlePaymentFailure = (err) => {
    console.error("Payment failed:", err);
    const errorMessage =
      err.description || err.reason || err.code || "Unknown payment error";
    setError(`Payment failed: ${errorMessage}`);
    setIsLoading(false);
  };

  // Validation checks
  useEffect(() => {
    if (!user?.userId) {
      navigate("/auth/login");
      return;
    }

    if (!cartItems || cartItems.length === 0) {
      navigate("/checkout/cart");
      return;
    }

    if (!selectedAddress) {
      navigate("/checkout/address");
      return;
    }
  }, [user, cartItems, selectedAddress, navigate]);

  if (isLoading) return <LoadingPage />;

  if (error) {
    return (
      <div className="min-h-screen bg-zinc-900 text-white flex items-center justify-center">
        <div className="text-center max-w-md mx-auto p-6">
          <h2 className="text-2xl font-bold text-red-400 mb-4">
            Payment Error
          </h2>
          <p className="text-gray-300 mb-6">{error}</p>
          <div className="space-x-4">
            <button
              onClick={() => {
                setError(null);
                setIsLoading(true);
                // Retry payment initialization
                window.location.reload();
              }}
              className="bg-blue-600 hover:bg-blue-700 px-6 py-2 rounded-lg"
            >
              Retry
            </button>
            <button
              onClick={() => navigate("/checkout/address")}
              className="bg-gray-600 hover:bg-gray-700 px-6 py-2 rounded-lg"
            >
              Go Back
            </button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-zinc-900 text-white px-4 py-8">
      <div className="max-w-5xl mx-auto">
        <h2 className="text-3xl font-bold mb-6 text-center">Review & Pay</h2>

        {/* Items List */}
        <div className="bg-zinc-800 rounded-xl p-6 shadow-lg mb-8">
          <h3 className="text-xl font-semibold mb-4">Items</h3>
          {cartItems.length === 0 ? (
            <p className="text-gray-400">No items in your cart.</p>
          ) : (
            <ul className="space-y-4">
              {cartItems.map((item, index) => (
                <li
                  key={item.id || item.productId || index}
                  className="flex items-center justify-between border-b border-gray-700 pb-4"
                >
                  <div className="flex items-center space-x-4">
                    <img
                      src={item.image || "/fallback.jpg"}
                      alt={item.productName}
                      className="w-20 h-20 object-cover rounded-lg"
                    />
                    <div>
                      <p className="font-medium">{item.productName}</p>
                      <p className="text-sm text-gray-400">
                        Size: {item.size} | Color: {item.color}
                      </p>
                      <p className="text-sm text-gray-400">
                        Qty: {item.quantity}
                      </p>
                    </div>
                  </div>
                  <div className="text-lg font-semibold">
                    ₹{(item.price * item.quantity).toFixed(2)}
                  </div>
                </li>
              ))}
            </ul>
          )}
        </div>

        {/* Address Section */}
        <div className="bg-zinc-800 rounded-xl p-6 shadow-lg mb-8">
          <h3 className="text-xl font-semibold mb-4">Shipping Address</h3>
          {selectedAddress ? (
            <div className="text-gray-300 leading-relaxed">
              <p className="font-semibold">{selectedAddress.fullName}</p>
              <p>{selectedAddress.street}</p>
              <p>
                {selectedAddress.city}, {selectedAddress.state} -{" "}
                {selectedAddress.postalCode}
              </p>
              <p>Phone: {selectedAddress.phone}</p>
              {selectedAddress.email && <p>Email: {selectedAddress.email}</p>}
            </div>
          ) : (
            <p className="text-gray-400">No address selected.</p>
          )}
        </div>

        {/* Payment Summary */}
        <div className="bg-zinc-800 rounded-xl p-6 shadow-lg">
          <h3 className="text-xl font-semibold mb-4">Payment</h3>
          <div className="space-y-2 mb-6">
            <div className="flex justify-between">
              <span>Subtotal:</span>
              <span>₹{cart.grandTotal?.toFixed(2) || "0.00"}</span>
            </div>
            <div className="flex justify-between text-lg font-bold border-t pt-2">
              <span>Total:</span>
              <span className="text-yellow-400">
                ₹{cart.grandTotal?.toFixed(2) || "0.00"}
              </span>
            </div>
          </div>

          <button
            className="w-full py-3 bg-yellow-600 hover:bg-yellow-500 rounded-lg text-white font-semibold transition disabled:opacity-50 disabled:cursor-not-allowed"
            onClick={handlePayment}
            disabled={!razorpayOrderId || isLoading}
          >
            {isLoading
              ? "Processing..."
              : `Pay ₹${cart.grandTotal?.toFixed(2) || "0.00"}`}
          </button>

          <div className="mt-4 text-center">
            <button
              onClick={() => navigate("/checkout/address")}
              className="text-gray-400 hover:text-white underline"
            >
              ← Back to Address
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PaymentPage;
